api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    title: 'Four in a row'
    description: "Four in a row is a two-player connection game in which the players first choose a color and then take turns dropping colored discs from the top into a seven-column, six-row vertically suspended grid. The pieces fall straight down, occupying the next available space within the column. The objective of the game is to be the first to form a horizontal, vertical, or diagonal line of four of one's own discs. Connect Four is a solved game. The first player can always win by playing the right moves."
    version: '1.0.0'

    collection:
        pagination:
            enabled: true
            client_enabled: true
            client_items_per_page: true
